codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        if_ci_failed: success
    patch:
      default:
        target: auto
        threshold: 10%
        if_ci_failed: success

